### ISSUE TITLE
Post Decision Stage: Keep the field 'release_submissions'  even if the venue is public

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1004]
Sometimes the PCs want to hide the rejected papers for a public venue so we need to give them the option of hiding them:

```
            'release_submissions': {
                'description': 'Would you like to release submissions to the public?',
                'value-radio': [
                    'Release all submissions to the public',
                    'Release only accepted submission to the public',
                    'No, I don\'t want to release any submissions'],
                'required': True
            }
```

- if Release all submissions to the public no action is taken
- if Release only accepted submission to the public, keep the accepted papers as they are and hide the rejected ones(visible to the PCs/AC/Reviewers/Authors)
- if 'No, I don\'t want to release any submissions', hide all the submissions.

**Comment by celestemartinez** [comment]
Now that `submission_readers` is being used instead in the post decision stage, this has been fixed.
