### ISSUE TITLE
Conflicts: check that profile emails are not obfuscated

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1011]
Otherwise a lot of invalid conflict can be detected. I suggest to check if there is at least one profile.content.emails that starts with ****@ and throw an exception.

**Comment by melisabok** [comment]
I think the function that get the profile info needs to make sure the emails are not obfuscated and throw an exception if they are.

**Comment by purujitgoyal** [comment]
Should we throw an exception even if only the username is obfuscated?

**Comment by melisabok** [comment]
What do you mean username? only email addresses are obfuscated. If you find at least one email that startwith '***' then you should throw an error.

**Comment by purujitgoyal** [comment]
by username I mean only the first part of email, i.e. part before `@`?

**Comment by melisabok** [comment]
ohhh YEs! we only obfuscate the first part of the email with ****

**Comment by purujitgoyal** [comment]
then it won't cause any problems with subdomains and I say we should remove the emails intersection as it's not necessary anymore.

**Comment by melisabok** [comment]
I don't understand your last comment, I think you should stop computing the conflicts.

**Comment by purujitgoyal** [comment]
What's the need of computing conflicts with emails since we are already using subdomains? Is there any particular case which is not covered by subdomains?

**Comment by melisabok** [comment]
sometimes email domains are not listed in the history of the profile so we should take it in account for conflict detection. There might be profiles with no history at all but one email address and we should use it as a domain.

**Comment by melisabok** [comment]
Maybe in the future, we should force the users to complete their history record if they enter an institutional email, after that we can ignore emails for conflict detection.

**Comment by purujitgoyal** [comment]
`get_profile_info` currently combines domains from both `profile.content['emails']` and `profile.content['history']`. 

The scenario you mentioned 
> sometimes email domains are not listed in the history of the profile so we should take it in account for conflict detection. There might be profiles with no history at all but one email address and we should use it as a domain.

I think is specific to `get_neurips_profile_info`, which we should change to what's happening in `get_profile_info`.

**Comment by melisabok** [comment]
What do you propose to change?

We also compute conflicts looking at the relations:

```
conflicts.update(author_relations.intersection(user_info['emails']))
conflicts.update(author_emails.intersection(user_info['relations']))
```

We can not get rid of the emails, at least for now.

**Comment by purujitgoyal** [comment]
I see, I have couple of questions first:

1. Do we store the obfuscated info anywhere?
2. What happens next if we raise an exception?

**Comment by melisabok** [comment]
1. No, the API obfuscate the emails when it returns the JSON in the GET /profiles call. Only if you have not permission to see the emails. 
2. The user that is running the code should see the exception and fix the permission issue.

**Comment by purujitgoyal** [comment]
Ah, since it's a permission issue, raising an exception makes sense. I'll add this. However, I'd still suggest removing email-email conflicts and updating the `get_neurips_profile_info`. Let me know if you want to do that.

**Comment by purujitgoyal** [comment]
Finally, is the obfuscation always `****@`?

**Comment by melisabok** [comment]
>  I'd still suggest removing email-email conflicts

- Co-authors with no profiles should use the email to compute domain conflicts.
- Profiles with no history must use the email to compute domain conflicts.

Do you want to remove this line?

`conflicts.update(author_emails.intersection(user_info['emails']))`

> updating the get_neurips_profile_info

Can you describe the proposed change here?

>  is the obfuscation always ****@

Yes.

**Comment by purujitgoyal** [comment]
I'll make a PR. It'll be easier to review the changes that way.
