### ISSUE TITLE
Hide submission fields in Withdrawn and Desk Rejected submissions

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1030]
If the venue required to hide more fields than just the authors then the withdrawn and desk rejected should hide them as well.

**Comment by melisabok** [comment]
When a submission is withdrawn or desk rejected, the submission invitation changes from Blind_Submission to Withdrawn_Submission or DeskRejected_Submission. When the process function of the withdraw makes this change, it has to hide the fields that were originally hidden in the blind submission:

https://github.com/openreview/openreview-py/blob/master/openreview/conference/templates/withdraw_process.py#L45

We can add a parameter in the process function called `HIDE_FIELDS` that is populated when the withdraw invitations are created:

https://github.com/openreview/openreview-py/blob/master/openreview/conference/builder.py#L852

https://github.com/openreview/openreview-py/blob/master/openreview/conference/builder.py#L889

**Comment by purujitgoyal** [comment]
Does this line have any significance?
https://github.com/openreview/openreview-py/blob/master/openreview/conference/invitation.py#L1459

**Comment by melisabok** [comment]
> Does this line have any significance?
https://github.com/openreview/openreview-py/blob/master/openreview/conference/invitation.py#L1459

No, this is a super invitation that works as a template and share behavior with all the paper invitation. In this case the process function that you need to edit is in the PaperWithdrawInvitation so you don't need to edit that line.
