### ISSUE TITLE
Getting all the notes for accepted paper

### ISSUE THREAD

**Issue by jbgao** [openreview/openreview-py#1036]
Here is from the example in the Openreview-py document

all_decision_notes = openreview.tools.iterget_notes(c, invitation = 'auai.org/UAI/2019/Conference/-/Paper.*/Decision')

It seems return an empty iterator?     What is the right invitation for this?

Thank you in advance.

JB

**Comment by melisabok** [comment]
Hi JB, 

The invitation is correct, UAI decisions are only visible to the authors and members of the committee. 

Best,

Melisa
