### ISSUE TITLE
Recruitment: catch the exception thrown by calling to conference.recruit_reviewers

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1055]
Catch the errors and post a comment in the request form with the description of the error. Otherwise the PCs don't know what is failing:

https://github.com/openreview/openreview-py/blob/master/openreview/venue_request/process/recruitmentProcess.py#L43

https://github.com/openreview/openreview-py/blob/master/openreview/venue_request/process/remindRecruitmentProcess.py#L19

You can reproduce this issue sending in the email template a word surrounded by {} where python format will try to replace it and  will throw a key error.

**Comment by purujitgoyal** [comment]
Is there a test for this? I tried doing what you suggested, but all the tests are still passing. I changed the email content here:
https://github.com/openreview/openreview-py/blob/927f30348f48d2895b4996f6b90690ed7b160868/openreview/venue_request/venue_request.py#L1008

**Comment by melisabok** [comment]
You need to do the recruitment through a venue request form. You can try to make it fail using test_venue_request.py

**Comment by purujitgoyal** [comment]
@melisabok This is what we want right?
<img width="1400" alt="Screen Shot 2022-01-06 at 10 55 30 AM" src="https://user-images.githubusercontent.com/21371064/148411298-22ca755f-b9c3-4eb0-9728-7fda10608824.png">

**Comment by melisabok** [comment]
It looks good! can we just print the exception stack trace? I'm not sure if "KeyError('program')" is clear enough. @celestemartinez what do you suggest?
