### ISSUE TITLE
Different domains from the same institution should be considered during conflict detection

### ISSUE THREAD

**Issue by carlosmondra** [openreview/openreview-py#1059]
We should probably have a list of domains that belong to the same institutions so that they are considered in the conficts.

This is from an email from Andrew:
**google.com and deepmind.com should be considered a conflict**

A researcher at DeepMind mentioned this to me, saying that this is a new problem, because deepmind.com just started to come into separate use in August 2021.

The researcher is a reviewer (or AC?) for ICLR, and said the lack of conflict detection is already causing problems.

**Comment by melisabok** [comment]
There is another case "ox.ac.uk" should be the same as "oxford.ac.uk".

**Comment by melisabok** [comment]
"fb.com" and "facebook.com" should be also the same.

**Comment by melisabok** [comment]
assigning this to @purujitgoyal , maybe you can find a list of institutions and their synonyms.  Or we can build it from scratch.
