### ISSUE TITLE
Custom Submission Name Change not Reflected in PC Console

### ISSUE THREAD

**Issue by nlbahy** [openreview/openreview-py#1074]
When a venue chooses to change their submission name to something other than 'Submission', that change is shown in the webfield code of the conference homepage and most group consoles (SUBMISSION_ID = correct_name) with the exception of the Program Chair console, which shows the default Submission ID.

**Comment by melisabok** [comment]
Does the PCs have a UI to change the submission name? 

I thought this values is hidden and it can be changes only by us.

**Comment by nlbahy** [comment]
It is hidden and only we can change it

**Comment by nlbahy** [comment]
Sorry, I'm not seeing this issue anymore. Maybe I noticed it happening on a PC console that had //webfield_template removed
