### ISSUE TITLE
Venue Request: call exceptions occurring in the process function and send an email to the venue organizers

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1084]
Similarly to what we did with the [recruitment process function](https://github.com/openreview/openreview-py/issues/1055), we should catch the exceptions and post a comment in the venue request with the description of the error. 

Do we need to post a comment if the process function finished successfully? Sometimes the users don't know if the changes are taking effect or there was an error. Thoughts? @celestemartinez @nlbahy

**Comment by celestemartinez** [comment]
I definitely agree with catching and posting the errors. With respect to posting a comment if there are no errors, I am not sure. It definitely wouldn't hurt but I feel like we will be spamming PCs with so many emails.

**Comment by nlbahy** [comment]
I agree with Celeste, I think they should only be notified if there is an error.

**Comment by purujitgoyal** [comment]
This would mean post a comment if there's an error for each process function [here](https://github.com/openreview/openreview-py/tree/master/openreview/venue_request/process), right?

**Comment by melisabok** [comment]
Right, not all the files need to handle the exception, only these ones:

postSubmissionProcess.py: process that is ran after the submission deadline
matchingProcess.py: process that initializes the matching data. 
revisionProcess.py: process that runs for all other stages: Review, MetaReview, Decision, etc.
