### ISSUE TITLE
Area Chairs Console: posted metareview is not shown in the status column

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1089]
If the metareview doesn't have the 'recommendation' field in the content the UI doesn't show there is a metareview posted. We should parametrize the field name and show the 'Edit/View' link even if there is not content field to show.

**Comment by melisabok** [comment]
This was happening in ARR November console: https://openreview.net/group?id=aclweb.org/ACL/ARR/2021/November/Area_Chairs

**Comment by zbialecki** [comment]
I see that for ARR the field 'overall_assesment' is used: https://api.openreview.net/notes?invitation=aclweb.org/ACL/ARR/2021/November/Paper531/-/Meta_Review

Are you saying you want the console to use this field name in the title? For example:
<img width="326" alt="Screen Shot 2022-01-13 at 7 28 51 PM" src="https://user-images.githubusercontent.com/86174/149430430-6e34f44b-d1ae-4db9-9f38-9b124828c00c.png">

Also I don't understand what you mean about showing the Read/Edit link even if the content field is missing. If there is no content field doesn't that mean the meta review has not been submitted yet? The current logic is to display the invitation URL in that case.

**Comment by melisabok** [comment]
The current logic show the Read/Edit link only if there is a recommendation value. I would like to show the link when there is always a metareview with or without a recommendation value.

**Comment by zbialecki** [comment]
OK, so how about this as a solution:

- Add a constant `METAREVIEW_DISPLAY_FIELD = 'recommendation'` to the top of the AC console webfield template
- Venues can overwrite this value with their chosen field name
- Change line 1181 (and any other lines that reference metareview.recommendation) to `cell3.recommendation = metaReview.content[METAREVIEW_DISPLAY_FIELD];`

**Comment by melisabok** [comment]
I agree with the changes but if forget to rename the variable and the metareview exists the link must be shown anyway. Can you have a default value for recommendation?

```
cell3.recommendation = metaReview.content[METAREVIEW_DISPLAY_FIELD] || 'something here';
```
