### ISSUE TITLE
suggested interpretation for details=official 

### ISSUE THREAD

**Issue by ajstent** [openreview/openreview-py#1107]
I think it would save _many calls_ to the API if details=official meant "return the details as well as the contents" or "return the deanonymized details" (if the caller is permissioned for this) in all calls, including get_notes. Right now, 
* if a program chair calls get_notes(forum=<forumid>), they get only _anonymized_ information for reviews
* by contrast, with openreview.tools.iterget_notes(client, invitation = '<venue>/-/Blind_Submission', details='original')}, they get the deanonymized details
This behavior should be made consistent.

**Comment by melisabok** [comment]
you can pass `details=original` to get_notes and get the same result.

**Comment by ajstent** [comment]
no; I tried that and it does not return the details

**Comment by ajstent** [comment]
more specifically, it returns 'None' in the details field

**Comment by melisabok** [comment]
Closing this issue because there is no bug detected.
