### ISSUE TITLE
SAC and AC identity: set assigned SAC as default reader of identities

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1113]
Otherwise they can not see their assigned papers and assigned AC in their consoles:

https://github.com/openreview/openreview-py/blob/master/openreview/venue_request/venue_request.py#L809

https://github.com/openreview/openreview-py/blob/master/openreview/venue_request/venue_request.py#L825

Make sure there is a test that verifies the SAC is not empty or the paper SAC groups are readable by the SAC user

**Comment by purujitgoyal** [comment]
Should I also raise an exception if the assigned SAC is not set as a reader like it's being raised for review identity right now?

**Comment by melisabok** [comment]
No, adding the assigned SAC as part of the default array is enough:  'default': ['Program Chairs'],

Before making the change you can reproduce the bug, checking the members of the paper SAC groups can not reader their own groups.
