### ISSUE TITLE
Decision Stage: Allow PCs to add 'Additional Decision Form Options' 

### ISSUE THREAD

**Issue by nlbahy** [openreview/openreview-py#1125]
PCs can currently add fields to Submission, Review, and MetaReview forms when running those stages from the venue request form. PCs are now requesting the same option for the Decision Stage, so that they can specify additional fields to be added to the decision form.

**Comment by melisabok** [comment]
You can take a look how the Review Stage is defined here: https://github.com/openreview/openreview-py/blob/master/openreview/venue_request/venue_request.py#L104 and apply it to the Decision stage here: https://github.com/openreview/openreview-py/blob/master/openreview/venue_request/venue_request.py#L419

Both stages call to the conference object where there is a function that creates all the invitations based on the parameters listed in their own stage class, like https://github.com/openreview/openreview-py/blob/master/openreview/conference/builder.py#L2063
