### ISSUE TITLE
Post Decision Stage: allow author notifications per decision option

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1153]
Program Chairs wants to send a different email notification per decision option: "Accept Oral", "Accept Poster", etc. 

The Post Decision Stage invitation could support these email templates, there should be one template per decision. 

I suggest that after the Decision Stage is created the Post Decision Stage can be defined. One markdown field per decision option can be added to the invitation. Markdown fields have the option to preview the changes so the PCs can check how the emails will look like. 

The process function of this invitation should send the emails notifications. We can add a new function in the conference class `conferencen.send_decision_notifications(templates)`

@nlbahy you can add instructions in the FAQ once this is complete.

**Comment by purujitgoyal** [comment]
Is there a default template for each decision that can be further customized or should I leave it empty or create one?

**Comment by melisabok** [comment]
having a default template is a good idea. I would suggest the following:

Accept papers:
```
Hi {{fullname}},

We are delighted to inform you that your submission {submission.number}: {submission.content['title']} has been conditionally accepted for presentation at {short_name} {year}. Congratulations!
```

Rejected papers:
```
Hi {{fullname}},

We regret to inform you that your submission {submission.number}: {submission.content['title']} was not accepted to the {short_name} {year}.
```

fullname: is automatically complete by the API server
submission number and title: must be replace by your code for each submission found
short_name and year: can be replace by the properties in the conference, conference.short_name and conference.year
