### ISSUE TITLE
Correct account to reveal obfuscated emails?

### ISSUE THREAD

**Issue by guopei** [openreview/openreview-py#1207]
In this [official doc](https://openreview-py.readthedocs.io/en/latest/_modules/openreview/tools.html) I see that "You do not have the required permissions as some emails are obfuscated. Please login with the correct account or contact support."

What kind of account should I have to reveal the obfuscated emails?

Thank you!

**Comment by melisabok** [comment]
You would need to be member of the Program Chairs group of an active venue.

**Comment by melisabok** [comment]
Closing this issue, if you have any questions about how to use openreview please post an issue here: https://github.com/openreview/openreview
