### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by casutton** [openreview/openreview-py#1226]
This code looks very useful, thanks! Scanning this repository quickly, I was not able to find a LICENSE.md file, or any indication of an open source license. Is it intended that the code in this repository is open source? If so, may I ask that you add a license to this repository? Thanks!

NB This is a different issue than #559 because here I'm asking only about the code, not the data.

**Comment by melisabok** [comment]
The license is listed here: https://github.com/openreview/openreview-py/blob/master/setup.py#L10

We can update the README file to make this more clear.

**Comment by casutton** [comment]
Thanks! Yes, I think it would be helpful to expose the license to the Github interface, e.g., by following the steps here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository#including-an-open-source-license-in-your-repository

**Comment by melisabok** [comment]
Nice!!!

I followed the instructions and we have a LICENSE.md file now. 

Thanks for the pointer!

**Comment by casutton** [comment]
Awesome, thanks for the fast response!
________________________________
