### ISSUE TITLE
Documentation: move the section "Retrieving all Official Reviews for a conference" to the new documentation site

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1244]
Rewrite the examples using `details=replies` instead of using a `regex` in the invitation filter.

**Comment by melisabok** [comment]
Why `replies` is more expensive than `directReplies`? 

Replies => they all share the same forum
DirectReplies => they all share the same forum and replyto == forum

**Comment by carlosmondra** [comment]
There are 2 reasons:
- When querying `directReplies` you will usually get back less Notes, so there is less data to transfer.
- Replies do share the same forum, but I cannot return all the forum Notes if the replies we are getting are the replies of a comment inside a forum. I can only return the replies that are replying to the comment, this requires a bit of extra processing in the backend before returning the replies.

**Comment by melisabok** [comment]
I see, I think we should use `replies` and `directReplies` for forum only, not replies.

**Comment by carlosmondra** [comment]
> I see, I think we should use `replies` and `directReplies` for forum only, not replies.

Do you mean that `details=replies` and `details=directReplies` should only work for notes where `note.id === note.forum`? 

What do we do when querying a comment and passing any of the details `replies` or `directReplies` and what would be the benefit?

**Comment by melisabok** [comment]
no benefit, only get the details for notes that are forums. I think see a case where someone would want to get the replies of a comment. They could get all the replies and browse the replies of the comment locally. This is a suggestion to reduce the amount of expensive queries.

**Comment by carlosmondra** [comment]
I think we can have a separate discussion about the behavior of `details` and `directReplies`.

I still think that Nadia should use `directReplies` to get the official  reviews. Is there a reason not to do it this way?

**Comment by melisabok** [comment]
No, no reason. Using `directReplies` should be in the doc.

**Comment by melisabok** [comment]
I guess this is done @nlbahy ?

**Comment by nlbahy** [comment]
Yes!
