### ISSUE TITLE
Recruitment invitation: tokens must be persisted with the API supported tokens

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1257]
API supports: {{firstname}} and {{fullname}}

Recruitment form supports: {name}, {accept_url} and {decline_url}.

I suggest to rename the recruitment token to be: {{fullname}}, {{accept_url}} and {{decline_url}} in order to be consistent with the API and the users don't get confused. 

When replacing {{fullname}} with the invitee name, I also suggest to ignore the replacement if the invitee has a profile. Let's delegate the replacement to the API so it can get the preferred name of the user.

Thoughts @carlosmondra ?

**Comment by carlosmondra** [comment]
Nope, I don't have any. I think for now this is fine. I guess later it would be nice if all the replacements are done in the same place.

**Comment by melisabok** [comment]
What do you mean make two separate functions?

I see that you already changed the journal code what is great.
