### ISSUE TITLE
Submission invitation readers should be values-copied

### ISSUE THREAD

**Issue by nlbahy** [openreview/openreview-py#1263]
For double-blind venues, the submission invitation must have values-copied for the readers field. Otherwise, the readers of the original submission will not be updated with revisions.

**Comment by melisabok** [comment]
How to reproduce this error:

1.  Use the test_neurips_conference.py test
2.  After the first deadline, the author can edit the submission using the Revision invitation and can add another author.
3.  The added author should try to access the submission and the Revision button.

Step 3 should fail now.

**Comment by purujitgoyal** [comment]
I was able to reproduce the error. The readers value is set using `submission_stage.get_invitation_readers` which uses `submission_stage.due_date` to identify whether the conference is under submission or not. I should change that to use the second due date, right @melisabok?

**Comment by melisabok** [comment]
I think for double blind venues the submissions readers should always be values-copied.

For single blind venues the submission readers should be values-copied until the first deadline. Between the first and second deadline they may want to choose another readers, for example add the ACs are readers so they can bid on papers.
