### ISSUE TITLE
Allow for more commonly used options in Rating/Confidence fields of Review form

### ISSUE THREAD

**Issue by nlbahy** [openreview/openreview-py#1285]
Some existing venues (for instance, ARR) are already using different formats for the rating/confidence fields. It would be nice if these could be supported: 

- Scores that use "=" instead of ":". ARR has been using the equals sign for every iteration
- Use of decimal places in rating (ie rating of 1.5)

**Comment by melisabok** [comment]
Is it possible to ask ARR to use `:` instead?

The webfields are parsing the data by `:` in order to show the stats. We could try to support both but I would prefer to use one single character. 

About the decimal places, is this not working?

**Comment by melisabok** [comment]
Some pointers about how to fix this issue. Most of the webfields parse the rating and confidence values:

https://github.com/openreview/openreview-py/blob/master/openreview/conference/templates/areachairWebfield.js#L289

and converts the parsed string to an int value. If we want to support decimal parts then we need to convert the string to a float.

**Comment by melisabok** [comment]
with API 2 this doesn't apply anymore, users can define the values and description in separate fields.
