### ISSUE TITLE
Allow PCs to undo paper withdrawals

### ISSUE THREAD

**Issue by nlbahy** [openreview/openreview-py#1294]
Program Chairs should have the ability to delete withdraw notes in order to un-withdraw submissions. The withdraw invitations need these changes in order to allow this: 

1. The PCs need to be made invitees of the withdraw invitations, and 
2. The PCs need to be made potential signatures of the withdraw invitation replies

**Comment by melisabok** [comment]
@purujitgoyal and @nlbahy:

With @carlosmondra we discussed that only the PCs should be able to undo the withdrawal. If the author needs to undo the action, they should contact the PCs and make the request. 

In NeurIPS we found several cases where authors undo withdrawn submissions that were not complete and they were taken into account in the paper matching.

**Comment by melisabok** [comment]
The UI checks if the note is writable to show the edit/trash button, it doesn't read the signatures info.
