### ISSUE TITLE
Single-blind venues should have multi-reply: True for their Revision invitation

### ISSUE THREAD

**Issue by nlbahy** [openreview/openreview-py#1299]
In between the abstract deadline and the submission deadline, Revision invitations are created for authors to edit their submissions. For single-blind venues, the Revision invitation needs to have multi-reply = True. This is handled in the setup_first_deadline_stage().

**Comment by melisabok** [comment]
To reproduce this:

- Go to a forum
- Click on "Revision" to post a revision
- The button "Edit Revision" doesn't appear. Instead it should appear the button "Revision"
