### ISSUE TITLE
Support Request Form: "Assigned <role>" should be preselected for each role's visibility

### ISSUE THREAD

**Issue by nlbahy** [openreview/openreview-py#1345]
When submitting a venue request form, PCs can select who should be able to see the identities of each role. For Senior Area Chairs, "Program Chairs" and "Assigned Senior Area Chairs" is preselected, which is correct. For Area Chairs, "Assigned Area Chairs" should be selected, and same for Reviewers.

**Comment by purujitgoyal** [comment]
I'm not sure about the reviewers, it will reveal the reviewers' identity to other reviewers as well.
