### ISSUE TITLE
Submission Revision stage: Add pdate when the revision is a Camera Ready Revision

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1368]
I suggest to add a checkbox to indicate if the revision stage is a camera ready stage. 

When this checkbox is selected the camera ready process function will update the bibtex and the pdate of the submission. 

Thoughts @nlbahy , @celestemartinez ?

**Comment by celestemartinez** [comment]
This sound good. Should the pdate be updated everytime a new camera ready revision is posted or only when the first revision is posted?
