### ISSUE TITLE
PC console - display of per decision progress is wrong

### ISSUE THREAD

**Issue by xkopenreview** [openreview/openreview-py#1404]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/60613434/191330603-dbbc28d3-a1a8-489d-87a2-bfdc25870754.png">

based on the class used, intention of pc console per decision progress is to have overall decision progress in one row and per decision progress in the row below
but the overall decision progress is not wrapped with a row div causing some per decision progress to be display at the wrong position

correct display should be
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/60613434/191331518-926190c9-ce43-4983-b759-27a8a01ad058.png">

**Comment by melisabok** [comment]
I don't think we should fix this issue in the webfield code, just make sure this is fixed in the component.

**Comment by xkopenreview** [comment]
i think this has been fixed in component so close
