### ISSUE TITLE
Recruitment: validate group not found error when adding a non existing member into a group

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1521]
Process function error when the email address is a DBLP url:

https://api.openreview.net/logs/process?id=Pxlk_Zr0ijO

https://api.openreview.net/notes?id=Pxlk_Zr0ijO

This error only occurs in the API 2.

**Comment by melisabok** [comment]
can you verify this is fixed?

**Comment by celestemartinez** [comment]
Yes, this is caught and printed in the status as 
`{
  "InvalidGroup": [
    "https://dblp.org/pid/XXX"
  ]
}`
