### ISSUE TITLE
Requesting all papers using Blind_Submission invitation does not return public withdrawn papers

### ISSUE THREAD

**Issue by dkobak** [openreview/openreview-py#1548]
Requesting all 2023 ICLR submissions like this: https://api.openreview.net/notes?invitation=ICLR.cc%2F2023%2FConference%2F-%2FBlind_Submission returns 3853 results which do not include publicly available widthdrawn submissions, e.g. https://openreview.net/forum?id=kRvZ2PcsxjJj. Is that on purpose? 

After the conference submission deadline, the exact same link https://api.openreview.net/notes?invitation=ICLR.cc%2F2023%2FConference%2F-%2FBlind_Submission used to return 4967 results. Is there any way to get that list now?

**Comment by melisabok** [comment]
Try using this call to get the withdrawn submissions:

https://api.openreview.net/notes?invitation=ICLR.cc%2F2023%2FConference%2F-%2FWithdrawn_Submission


Desk Rejected:

https://api.openreview.net/notes?invitation=ICLR.cc%2F2023%2FConference%2F-%2FDesk_Rejected_Submission

**Comment by dkobak** [comment]
Wow, great, thanks a lot! I get 1085 withdrawn and 18 desk rejected, so 3853+1085+18 = 4956 together, which is very close to the number of blind submissions I got with `Blind_Submission` shortly after the submission deadline (4967). So this solves the issue for me!

I am still wondering why `Blind_Submission` query does not return ALL submissions anymore, but practically speaking it isn't very important for me.

**Comment by melisabok** [comment]
Blind_Submission is being used to represent active submissions.

We recently launched a new API that is being used for TMLR and ICML and you will be able to query all the notes together.

**Comment by dkobak** [comment]
Thanks a lot, Melisa! Let me close this issue.

**Comment by dkobak** [comment]
Dear Melisa, I stumbled upon a related issue: I cannot get ICLR submissions to 2017 and earlier, e.g. 

https://api.openreview.net/notes?invitation=ICLR.cc%2F2017%2FConference%2F-%2FBlind_Submission

returns 0 hits. It does work for 2018+ though. Should I use something else instead of `Blind_Submission` for 2017 (and also instead of `Withdrawn_Submission`, `Desk_Rejected_Submission`)?
