### ISSUE TITLE
Venue class: use domain.content.contact.value as replyTo for all the email notifications

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1553]
For all the email notification being sent on behalf of a venue, we should add the replyTo parameter and use the contact info. So users can contact the organizers clicking on reply. 

With the exceptions of the AC invite assignments?

**Comment by enrubio** [comment]
@melisabok @celestemartinez 

To do this, would I add the `replyTo` parameter to _all_ `post_message` function calls in the openreview/venue directory?

Also, what does "AC invite assignments" mean? Does that mean when a PC invites an AC or when an AC invites a reviewer? And where can I find that?

**Comment by melisabok** [comment]
> would I add the replyTo parameter to all post_message function calls in the openreview/venue directory?

Yes, they are mostly process function stored in the process folder

> Also, what does "AC invite assignments" mean? Does that mean when a PC invites an AC or when an AC invites a reviewer? And where can I find that?

When a AC invites a reviewer to review a specific paper, this is usually done through the "Invite_Assignment" invitation. 

You can see some examples here: https://github.com/openreview/openreview-py/blob/master/tests/test_icml_conference.py#L1438

The invite assignment invitation is an edge invitation that is being used to recruit external reviewer. When an edge is created using this invitation, there is a process function that runs and sends an email to the edge.tail(invitee). But I think in this case we can add the contact info as replyto or should we use the ac email if the ac identity is visible to the reviewers? cc @celestemartinez

**Comment by enrubio** [comment]
@melisabok @celestemartinez what do you think should be used in the replyTo for Invite Assignment? should it be the contact info or the AC email (if visible)?

Also, how would I check if AC identities are visible to reviewers? Do I check if `area_chair_identity` in the request form is set to `All Reviewers`? And would the signature of the assignment edge contain the AC that assigned the reviewer?

**Comment by celestemartinez** [comment]
We store who can see AC identities in `area_chair_identity_readers`, we could store this in the group content or the Invite Assignment invitation so we can check in the process function if the reviewer should see the AC identity. 

I think it should be fine to use the AC email if identities are revealed to reviewers.
