### ISSUE TITLE
Venue recruitment: "Invalid group id" when the invitee is an email address with uppercase

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1567]
This issue happened with NeurIPS 2023 SAC recruitment, the PCs sent the invitation to an email address with uppercase, the user was invited and added to the group correctly but the url contained the email in uppercase. 

I think the bug is when creating the url and the hash key we should send the email all in lowercase.

**Comment by celestemartinez** [comment]
I was getting another error when trying to send the email, since the lower case email was being added to the group:
<img width="1224" alt="Screen Shot 2023-02-21 at 11 10 28 AM" src="https://user-images.githubusercontent.com/32438984/220421768-b94310cc-9d5e-4253-ae98-e34e24291c4c.png">

**Comment by melisabok** [comment]
so why is it working in the live site?

https://openreview.net/forum?id=u4QodE3u4r&noteId=d2yfaVgCbY
