### ISSUE TITLE
Venue: check if the invite_assignment edge exist when accepting/declining invitation 

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1576]
To avoid not found errors in post process functions, I suggest to check if the invitation assignment edge for the user and submission id exists. 

We can get the user and the submission id from the url. If no edge found for that user, we can try to search the edge by profile.id. Sometimes there is a profile merge and edges are renamed.

How to reproduce this issue?

- AC invites reviewer.
- AC removes invite assignment edge.
- Reviewer accepts the invitaiton.

Expected:

- Reviewer should get an error after clicking the button saying "invitation no longer exists"

Another improvements:

- if the user clicks on "Accept" and the invitation edge says "Accepted" throw an error "You already accepted this invitation"
- if the user clicks on "Declined",  no comment is written and the invitation edge says "Declined" throw an error "You already declined the invitation".
- if the user click on "Declined and there is a comment, I would let the user decline again so the reason can be shared with the AC.

This way we avoid too many recruitment notes and emails.

**Comment by celestemartinez** [comment]
Should we do the same with 'Pending Sign Up' and 'Conflict Detected' labels? Maybe for 'Pending Sign Up' we would like to allow them to re-accept since they might have created a profile? or should we wait for the job to check? Same with 'Conflict Detected' not sure if there is any time we would like them to try to re-accept an invitation

**Comment by melisabok** [comment]
I see that you are already validating these states and the error messages look good to me. 

If a conflict is accepted or the status is pending signup, they shouldn't accept the invitation again.
