### ISSUE TITLE
Venue: decision stage should let the PCs decide which decision options are representing an acceptance

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1664]
Currently the decision option that contains the work "Accept" is considered an acceptance. But some venues want to decide their own labels without the word "Accept".

@celestemartinez is suggesting that PCs should indicate this while configuring the decision stage or post decision stage? there should be a dropdown where they can select the decision options considered as acceptance.

**Comment by enrubio** [comment]
Fixed in #2115
