### ISSUE TITLE
Venue Recruitment: updating the invitation content

### ISSUE THREAD

**Issue by celestemartinez** [openreview/openreview-py#1731]
We only update the invitation content when the reduced load has changed, but even then we only repost the new reduced load. This means that the fields `overlap_committee_id` and `overlap_committee_name` are never updated, even if the PCs change this in the request form recruitment:

https://github.com/openreview/openreview-py/blob/c448f3cc285675879f6576abcc71ece9dd035ddb/openreview/venue/invitation.py#L769

**Comment by melisabok** [comment]
We should check if these values change and add the changes to the edit!
