### ISSUE TITLE
Outdated documentation api.v1 vs api.v2

### ISSUE THREAD

**Issue by manuelhaussmann** [openreview/openreview-py#1747]
Hi,

the documentation [here](https://docs.openreview.net/getting-started/using-the-api/notes) still seems to follow the old interface, while other parts discuss both v1 and v2. Is there a current equivalent to the example provided there, given that the `regex` parameter is no longer available in v2?

Thanks for a great tool!

**Comment by melisabok** [comment]
`regex` was replaced by `prefix` that is less expensive.

For you API 2 you need to use another client: https://openreview-py.readthedocs.io/en/latest/api.html#openreview.api.OpenReviewClient

We will update the documentation soon, thanks!

**Comment by manuelhaussmann** [comment]
Perfect, thanks!
