### ISSUE TITLE
Add members to a group: remove duplicates before posting the edit

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1761]
Otherwise the API doesn't let you send repeated members.

**Comment by celestemartinez** [comment]
Does this refer to `add_members_to_group`? Because we remove duplicates here: https://github.com/openreview/openreview-py/blob/ea7ae8dc08d7ffec267a92e0ce996cf28a1c8e45/openreview/api/client.py#L1619

Is the error in the else? In which scenarios do groups do not have invitations?
