### ISSUE TITLE
Submission keywords field: don't let empty string to be allowed in the keywords array

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1799]
Currently the default submission form defines the keyword field as: https://github.com/openreview/openreview-py/blob/master/openreview/stages/default_content.py#L467

This allows the value `[""]` to be valid for the API validation and we shouldn't allow it. My recommendation is to change the regex definition to be `.+` as non empty strings.

**Comment by enrubio** [comment]
Should the keywords field also be changed for `submission`? They have the same regex:

https://github.com/openreview/openreview-py/blob/833218d78c8421492c106cd420b991c6bd728e97/openreview/stages/default_content.py#L405

**Comment by melisabok** [comment]
yes, you could, however `submission` is being used in the API 1 only so it is deprecated.
