### ISSUE TITLE
How to get_all_notes for ICML23?

### ISSUE THREAD

**Issue by tieqiao** [openreview/openreview-py#1808]
accepted_notes = client.get_all_notes(content={ 'venueid': 'ICML.cc/2023/Conference'})
Getting V1 Notes: 0it [00:00, ?it/s]

This code works for ICLR but not for ICML.
accepted_notes = client.get_all_notes(content={ 'venueid': 'ICLR.cc/2023/Conference'})

**Comment by carlosmondra** [comment]
ICML is using the API V2 of OpenReview. That means that the way you instantiate the client should be different:
https://docs.openreview.net/getting-started/using-the-api/installing-and-instantiating-the-python-client

**Comment by carlosmondra** [comment]
Please carefully look at the way in which an API V2 client is instantiated from the link I shared with you.
Also, notice that the schema of the invitations and the notes changes for the new API so your code will not work the way you shared it. The docs also contains what the new schema looks like, so that you can update the code accordingly.

**Comment by tieqiao** [comment]
But this is an original example in the tutorial. The function signature doesn't have a regex key.

May you please directly tell me how to solve this? I believe it only needs one line of code if the function exists.

I have read through the document. And this code also doesn't work for a V2 invitation like ICML.

```
invitations = client.get_invitations(
        regex='ICML.cc/2023/Conference/.*',
        limit=10,
        offset=0)
```

**Comment by carlosmondra** [comment]
From the docs:


https://docs.openreview.net/getting-started/using-the-api/installing-and-instantiating-the-python-client
Instantiate the client
```py
import openreview

# API V2
client = openreview.api.OpenReviewClient(
    baseurl='https://api2.openreview.net',
    username=<your username>,
    password=<your password>
)
```

https://docs.openreview.net/getting-started/using-the-api/notes/getting-all-submissions
Get all submissions.
```py
submissions = client.get_all_notes(invitation="ICML.cc/2023/Conference/-/Submission")
```

Not sure what tutorial you were following. Can you please share the link to see if it needs to be updated or if it has an error?

**Comment by tieqiao** [comment]
Good. Thanks.

https://docs.openreview.net/getting-started/using-the-api/notes

This page is a little bit confusing.
```
regex='ICLR.cc/2019/Conference/.*
```
what can be .*

**Comment by carlosmondra** [comment]
Thanks for sharing the link. We will update the docs to make it clearer.
