### ISSUE TITLE
Modify recruitment invitation of request form to include field for accepting with reduced load

### ISSUE THREAD

**Issue by enrubio** [openreview/openreview-py#1813]
This issue is based on this comment by @melisabok in https://github.com/openreview/openreview-web/issues/1554#issuecomment-1675147456_

>@racheljsmart I wonder if you can guide @enrubio to integrate this in the "Recruitment" invitation of the request form. We should add a new field, probably a radio button with options "Yes" and "No" and description: "Select yes if you want invitee users to select their reduced load on accept otherwise they can do it on decline only". If this value is yes then pass true to allowAcceptWithReducedLoad.

>Otherwise you will need to setup this value manually.

**Comment by racheljsmart** [comment]
We can add the field "invitee_accept_reduced_load" to the recruitment content between "invitee_reduced_load" and "invitee_details" https://github.com/openreview/openreview-py/blob/d2aeafe22d4f3b72492421bbd022403181ff5d21/openreview/venue_request/venue_request.py#L1652

'invitee_accept_reduced_load': {
                'description': 'Select "yes" if you want invited users to chose their reduced load when accepting, otherwise this will default to selecting a reduced load when declining.',
                'value-radio': ['Yes', 'No'],
                'default': 'No',
                'required': False,
                'order': 5
            }
