### ISSUE TITLE
Recruitment: line with only a comma

### ISSUE THREAD

**Issue by celestemartinez** [openreview/openreview-py#1849]
A PC tried recruiting  a bunch of reviewers, but one line consisted of only a comma. This gave error because after we split at the commas, we assume the length >0.

https://github.com/openreview/openreview-py/blob/7c297c243415da1c781ce6b891032931fe71e81d/openreview/venue_request/process/recruitmentProcess.py#L37-L43

I think we can just ignore the line if len(details)==0.

**Comment by melisabok** [comment]
Can you paste an example if invitee details so we can reproduce it?

**Comment by celestemartinez** [comment]
Example:

```
emilia@mail.com, Emilia Rubio
celeste@mail.com,Celeste Martinez
,
melisa@mail.com,Melisa Bok
```

in `invitee_details`
