### ISSUE TITLE
Blind_Submission invitation does not return any papers for ICLR pre-2018

### ISSUE THREAD

**Issue by dkobak** [openreview/openreview-py#1860]
I can get all non-withdrawn and non-desk-rejected submissions to ICLR 2018+ using the `Blind_Submission` invitation (and I can use `Withdrawn_Submission` for the withdrawn ones and `Desk_Rejected_Submission` for the desk rejected ones):

https://api.openreview.net/notes?invitation=ICLR.cc%2F2018%2FConference%2F-%2FBlind_Submission
https://api.openreview.net/notes?invitation=ICLR.cc%2F2019%2FConference%2F-%2FBlind_Submission
https://api.openreview.net/notes?invitation=ICLR.cc%2F2020%2FConference%2F-%2FBlind_Submission
https://api.openreview.net/notes?invitation=ICLR.cc%2F2021%2FConference%2F-%2FBlind_Submission
https://api.openreview.net/notes?invitation=ICLR.cc%2F2022%2FConference%2F-%2FBlind_Submission
https://api.openreview.net/notes?invitation=ICLR.cc%2F2023%2FConference%2F-%2FBlind_Submission

However, this does not work for preceding years, and all the following links return 0 hits:

https://api.openreview.net/notes?invitation=ICLR.cc%2F2013%2FConference%2F-%2FBlind_Submission
https://api.openreview.net/notes?invitation=ICLR.cc%2F2014%2FConference%2F-%2FBlind_Submission
https://api.openreview.net/notes?invitation=ICLR.cc%2F2015%2FConference%2F-%2FBlind_Submission
https://api.openreview.net/notes?invitation=ICLR.cc%2F2016%2FConference%2F-%2FBlind_Submission
https://api.openreview.net/notes?invitation=ICLR.cc%2F2017%2FConference%2F-%2FBlind_Submission

Should I use something else instead of `Blind_Submission` here (and also instead of `Withdrawn_Submission` and `Desk_Rejected_Submission`)?

**Comment by dkobak** [comment]
Thank you! I did try `Submision` which did not work, and I did not try the lower-case version: `submission` :-)

**Comment by melisabok** [comment]
No worries for next ICLR iterations you can use the content.venueid and our new version of the API:

https://api2.openreview.net/notes?content.venueid=ICLR.cc/2024/Conference/Submission

Submissions are not public yet but once they are released, you should get results.

**Comment by dkobak** [comment]
Thanks. I was wondering why the submissions for ICLR 2024 are still not public. Do you know when they should be released? I think previously they used to be public immediately after the deadline.

**Comment by melisabok** [comment]
ICLR 2024 submissions are public now.

**Comment by melisabok** [comment]
Hi @dkobak ,

ICLR 2024 have now decisions and they are not under review anymore, to query them you just need to use the ICLR group id:

https://api2.openreview.net/notes?content.venueid=ICLR.cc/2024/Conference

**Comment by melisabok** [comment]
For rejected submissions use venueid: ICLR.cc/2024/Conference/Rejected_Submission

**Comment by dkobak** [comment]
Thanks a lot @melisabok!

To double-check, I got the following counts:

https://api2.openreview.net/notes?content.venueid=ICLR.cc/2024/Conference -- 2261
https://api2.openreview.net/notes?content.venueid=ICLR.cc/2024/Conference/Rejected_Submission -- 3490
https://api2.openreview.net/notes?content.venueid=ICLR.cc/2024/Conference/Withdrawn_Submission -- 1515
https://api2.openreview.net/notes?content.venueid=ICLR.cc/2024/Conference/Desk_Rejected_Submission -- 38

2261 + 3490 + 1515 + 38 = 7304

That's exactly the same number (7304) as I previously got via

https://api2.openreview.net/notes?content.venueid=ICLR.cc/2024/Conference/Submission

Thanks a lot!
