### ISSUE TITLE
Remove reviewers_proposed_assignment_title when assignments are deployed

### ISSUE THREAD

**Issue by racheljsmart** [openreview/openreview-py#1864]
This issue came up in the ICLR 2024 Conference. After the assignments were deployed, the reviewers_proposed_assignment_title was not deleted from group.content and the edge browser link was not updated.

**Comment by celestemartinez** [comment]
We should check if the assignments being deployed are for reviewers. If so, we should delete `reviewers_proposed_assignment_title` from the venue group.

Deployment happens in `deploy_assignments()`
