### ISSUE TITLE
Comment preprocess: check all group exists before sending email

### ISSUE THREAD

**Issue by celestemartinez** [openreview/openreview-py#1867]
**Edited: we should check all groups we are sending emails to exist, not only the Reviewers/Submitted group.**

In the comment preprocess, we send emails to the comment readers. Reviewers/Submitted groups are created when reviews are posted, so this group might not exist if comments are posted before reviews. 
We should check the group exists before sending the email.

**Comment by melisabok** [comment]
@celestemartinez could you provide a use case for Emilia to reproduce this issue? I don't see that this is happening now.

**Comment by celestemartinez** [comment]
This happened when a user tried to post a comment visible to Reviewers/Submitted. However, the Reviewer/Submitted groups are created when a review is posted. If the comment is posted before any reviews are posted for that paper, we will get this error. 

I don't think PCs usually enable comments that early in the venue's workflow, but this error will happen if they do. 

You can use the `test_iclr_conference_v2.py` to test this. Try to post a comment with Reviewer/Submitted to any paper except Paper#1.
