### ISSUE TITLE
Invite Assignment: fix key error when abstract is not present

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1869]
Check this process function error:https://api2.openreview.net/logs/process?id=8PVIRQUTK0Udwn

**Comment by enrubio** [comment]
In the 2nd log you listed, are you saying there's a key error there as well? I don't see it in that one

**Comment by melisabok** [comment]
Ooops, wrong link: check this one: https://api2.openreview.net/logs/process?id=BiSMuQN2Yk

**Comment by melisabok** [comment]
Search in all the openreview-py code: `['abstract']` and then replace with `get('abstract', {})`
