### ISSUE TITLE
Too many progress bars when using get_profiles + with_publications=True

### ISSUE THREAD

**Issue by yoshitomo-matsubara** [openreview/openreview-py#1903]
Currently, get_profiles function prints a progress bar per profile at
https://github.com/openreview/openreview-py/blob/master/openreview/tools.py#L210
and
https://github.com/openreview/openreview-py/blob/master/openreview/tools.py#L214
, which makes terminals twitch and slow. e.g., tens of thousands IDs to process.

Can you use a progress bar per concurrent_requests
i.e., there will be only two progress bars: processes for `notes_v1` and `notes_v2` 
or add an option not to show progress bars when using get_profiles with `with_publications=True` ?

**Comment by yoshitomo-matsubara** [comment]
Thanks for the fix! I recently updated the local package, but didn't notice that there were a few more releases after that

It reduced the number of progress bars significantly though it still shows many progress bars. Is it what it is?

**Comment by melisabok** [comment]
the progress bar is being shown if there is a profile that contains more than 1000 publications.

**Comment by yoshitomo-matsubara** [comment]
I see, that's what "there are more objects than the first page" in the comment means. Thank you for the clarification!
