### ISSUE TITLE
APIv2 note.invitations not working as documented

### ISSUE THREAD

**Issue by adinriv** [openreview/openreview-py#1924]
I'm following the instructions to obtain the camera ready status of the accepted submissions for my venue (NLDL2024, venue ID `NLDL.org/2024/Conference`) according to: https://docs.openreview.net/how-to-guides/data-retrieval-and-modification/how-to-view-camera-ready-revisions

However, the `note.invitation` (note that the documentation refers to `.invitations` that is nonexistent) is not populated despite the authors having submitted a camera ready version.

**How am I supposed to check if the submission was updated with the camera ready?**  Should I follow another reference?

**Comment by racheljsmart** [comment]
Hi Adin,

I think there might be a pair of brackets missing in part of the documentation code, however it would depend on what you ran. When I checked your venue I got three papers that were modified with the /-/Camera_Ready invitation. Can you email us at info@openreview.net and share the code you used?

-Rachel

**Comment by adinriv** [comment]
Thanks for the information.  I sent an email with the lines I'm using, but they are pretty much the same as what is in the docs.  The error is about `AttributeError: 'Note' object has no attribute 'invitations'`.  Let me know if you need more information though.  

For instance

```python
accepted_notes = client.get_all_notes(content={'venueid':venue_id} )
for note in accepted_notes:
    if note.invitations is not None:
        print(note.number)
```

or 

```python
accepted_notes = client.get_all_notes(content={'venueid':venue_id} )
camera_ready_notes = []
for note in accepted_notes:
    camera_ready_invitation = f'{venue_id}/Submission{note.number}/-/Camera_Ready'
    if camera_ready_invitation in note.invitations:
        print(note.number)
        camera_ready_notes.append(note)
print(camera_ready_notes)
```

both stop when I try to access `note.invitations`.

**Comment by melisabok** [comment]
Make sure you are using the API 2 client: https://github.com/openreview/openreview-py/blob/master/openreview/api/client.py

**Comment by adinriv** [comment]
I think I do.

I'm loading it through

```python
import openreview

client = openreview.Client(baseurl='https://api2.openreview.net', username='user', password='pass')
```

Should it be loaded or accessed in a different way?

**Comment by melisabok** [comment]
You are using another client class(API 1 only), you should use:

```
openreview.api.OpenReviewClient(baseurl='https://api2.openreview.net', username='user', password='pass')
```
