### ISSUE TITLE
Add recommendation field name configuration to Meta Review Stage

### ISSUE THREAD

**Issue by racheljsmart** [openreview/openreview-py#1930]
Add a configuration setting "Meta Review Recommendation Field Name" to the Meta Review Stage that sets 'recommendation' as the default and allows PCs to change the value, like they do in the Review Stage configuration.

'recommendation' is stored in group content.meta_review_recommendation and is called by the PC, SAC, and AC consoles for display.

**Comment by celestemartinez** [comment]
Fixed here: https://github.com/openreview/openreview-py/pull/2025
