### ISSUE TITLE
Remove apiVersion config

### ISSUE THREAD

**Issue by xkopenreview** [openreview/openreview-py#1941]
i think apiVersion config can be removed from the following templates:

- eventCertificationWebfield
- homepage
- areachairsWebfield
- ethicsReviewersWebfield
- paperBidWebfield
- profileBidWebfield
- programChairsWebfield
- publicationChairWebfield
- reviewersWebfield
- seniorAreaChairsWebfield

**Comment by melisabok** [comment]
Sounds good!
