### ISSUE TITLE
Venue request: let's the PC select a list of possible licenses. 

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1972]
There is a request where the PCs wants the authors to decide which license to use. 

I suggest the PCs can declare a comma separated list of licenses and we will render a dropdown so the author can select one of them. So "Submission License" can be editable and the PCs can enter multiple values.

**Comment by melisabok** [comment]
@xkopenreview can the license field be a param that renders a dropdown?

**Comment by xkopenreview** [comment]
> @xkopenreview can the license field be a param that renders a dropdown?

yes, but not in the form of comma separated string
it should be in the form of enum object(value+description) array

**Comment by melisabok** [comment]
Awesome, so @enrubio you would need to translate the value from the request form: license1, license2, license3
to the following:

license: {
   param: {
       enum: [
          { value: license1, description: license1 },
          { value: license2, description: license2 },
          { value: license3, description: license3 }
       ]
    }
}

if the textbox has one single license then it should like it is right now:

license: license1

**Comment by enrubio** [comment]
- Issue was resolved with this PR: #1977
