### ISSUE TITLE
How to get the submission id of all venues?

### ISSUE THREAD

**Issue by UWzhuojiu** [openreview/openreview-py#1979]
Hi,

I tried to follow [this link](https://docs.openreview.net/how-to-guides/data-retrieval-and-modification/how-to-get-all-submissions) to get all submissions of some of the venues. 

And I have tried AP1 V1 and V2. With API V1, I can only get some of them with "Blind_Submission" and "Submission", so I tried all venues, and it seems only 35%. (I also tried 'submission' and get 7 more result) And with API V2, only venues in 2023 or later have "**content**", so I still can't get the ''submmision_name" of venues before 2023.

Can anyone tell me how to get the ''submmision_name" of venues before 2023? 

Thanks!

**Comment by racheljsmart** [comment]
Hello,

content['submission_name']['value'] only works for venues that were created using API 2. We started creating venues using API 2 in 2023.

Whether or not you can get submissions also depends on the permissions and readership of that venue. If you are trying to get submissions for all venues, if submissions are not public then you will likely retrieve a small number of submissions.

If the venues did not configure the submissions to be public, submission data, even a count of submissions, is not accessible unless you are a program chair for the venue.

Best,
Rachel

**Comment by UWzhuojiu** [comment]
Thanks for your response.
