### ISSUE TITLE
Venue: let users delete invite assignments edges

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#1981]
This way they can cancel an invitation to an emergency reviewer before accepting it.

**Comment by celestemartinez** [comment]
We should:
- add ACs (and SACs?) as writers of Invite_Assignment invitations
- check in the preprocess function if the reviewer has accepted the invitation. If they have, throw an error saying the edge can't be deleted
- if invite assignment is still pending, the AC can delete the edge  and cancel the invitation

**Comment by celestemartinez** [comment]
Done here: #1999
