### ISSUE TITLE
Paper Matching Setup: don't let run more than one setup per group at the same time

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#2016]
PCs should wait until the setup matching is complete to run a new one for the same group id. 

I think they get anxious because they don't see a status so they run it and this takes a lot of resources of our expertise API. Also there could be race condition issues when saving the edges.

I suggest to add a validation in the pre process function that checks if there is a setup matching note with no status and throw an error. @celestemartinez @enrubio thoughts?

**Comment by celestemartinez** [comment]
This is a good idea. We would only need to check the last posted `Paper_Matching_Setup` for that `matching_group` and check if there is a `Paper_Matching_Setup_Status` note posted already.
