### ISSUE TITLE
ICLR 2024 withdrawn submissions are not de-anonymized

### ISSUE THREAD

**Issue by dkobak** [openreview/openreview-py#2045]
All withdrawn (and also desk rejected) submissions to ICLR 2024 are not de-anonymized. Example: https://openreview.net/forum?id=uEYxHVQJF4. List of all withdrawn submissions: https://api2.openreview.net/notes?content.venueid=ICLR.cc/2024/Conference/Withdrawn_Submission.

This was not the case for previous ICLR conferences: all submissions from 2017 to 2023 are de-anonymized, including all the withdrawn and desk rejected ones.

Did the policy change in 2024, or is it a database mistake? Are the withdrawn/desk-rejected 2024 submissions going to be de-anonymized?

**Comment by dkobak** [comment]
Update: according to https://iclr.cc/Conferences/2024/CallForPapers,
> after the paper submission deadline, if an author chooses to withdraw a submission, it will remain hosted by OpenReview in a publicly visible "withdrawn papers" section. Like on arXiv, submissions to ICLR cannot be deleted or modified. Withdrawn papers will be de-anonymized immediately.

So my understanding is that all submissions should have been de-anonymized by now.

**Comment by melisabok** [comment]
Hi @dkobak , you should contact the ICLR 2024 organizers.

**Comment by dkobak** [comment]
Thanks @melisabok, I did contact them. They said (on Twitter: https://twitter.com/iclr_conf/status/1770500383997382808)

> there was a minor error in setting a flag. Should be remedied shortly. Thanks for catching this.

Unfortunately, nothing has changed yet. I am letting you know just in case.

**Comment by melisabok** [comment]
We are working on it, assigning this to @celestemartinez

**Comment by celestemartinez** [comment]
Desk-rejected and withdrawn papers have been released.

**Comment by dkobak** [comment]
@celestemartinez Oh that's wonderful, thanks a lot!

Just checking the total number of papers now, https://api2.openreview.net/notes?content.venueid=ICLR.cc/2024/Conference/Withdrawn_Submission returns 1603 papers and Desk_Rejected_Submission returns 53. Rejected_Submission returns 3487 and Conference returns 2261. In total, that's 7404, which is 100 more than I had a few days ago (before you did de-anonymization) and also 100 more than https://api2.openreview.net/notes?content.venueid=ICLR.cc/2024/Conference/Submission returned before the decisions were announced. See https://github.com/openreview/openreview-py/issues/1860#issuecomment-1992576835.

What can explain this discrepancy?

**Comment by celestemartinez** [comment]
@dkobak not all withdrawn/desk-rejected submissions were public, so when you queried them [here](https://github.com/openreview/openreview-py/issues/1860#issuecomment-1992576835), you did not get all withdrawn submissions that should have been visible to you. I deanonymized withdrawn and desk-rejected submissions, as well as made them public. 

Let me know if this does not answer your question.
