### ISSUE TITLE
Decision notifications: Update message posted to request form

### ISSUE THREAD

**Issue by celestemartinez** [openreview/openreview-py#2081]
We removed the parentGroup when email authors about decisions, so we need to update the comment posted to the request form, as this is confusing to PCs.

<img width="1163" alt="Screen Shot 2024-04-08 at 12 10 17 PM" src="https://github.com/openreview/openreview-py/assets/32438984/87b0f0e6-b847-4267-bcc9-81964f60d21e">

**Comment by melisabok** [comment]
Is there a reason why we removed the parentGroup? 

I don't think there is another way to check if the messages were sent.

**Comment by melisabok** [comment]
Ohhhh I remember now. I would add it back, once we add the invitation id, the API doesn't validate by parentGroup anymore so it should be efficient.

**Comment by melisabok** [comment]
@celestemartinez is there a reason why the post_decision_stage runs with the super user permissions? I would like to use the token of the PCs to make changes in the submissions and send messages.

**Comment by melisabok** [comment]
I'm reverting my change: https://github.com/openreview/openreview-py/pull/2086 and hoping that a large conference uses the message invitation to send the emails.

**Comment by celestemartinez** [comment]
> @celestemartinez is there a reason why the post_decision_stage runs with the super user permissions? I would like to use the token of the PCs to make changes in the submissions and send messages.

Not sure, we can probably change this. Does this mean changing the Post_Decision_Stage signatures in the request form? Would this be changed to be the venue id or the PC group id?

**Comment by melisabok** [comment]
I'm realizing that all the stages have the super user as signature :(

For the new venue management we need to make sure we don't use the super user to run venue workflows. We should use the super user to deploy the venue only.

Closing the issue because we are reverting my previous change.
