### ISSUE TITLE
Custom Stage: adding PCs as signatures

### ISSUE THREAD

**Issue by celestemartinez** [openreview/openreview-py#2083]
Right now, we always add the PCs as invitees, readers and signatures of all CustomStage invitations.

There was an issue where the PC submitted the review revision of a review. This resulted in an error when `invitation_edit_process.py` tried to update all invitations and notes.

Two solutions:
1. Allow PCs to be signatures always in the CustomStage and fix `invitation_edit_process.py`. The only issue with this, is that if the field has readers `"${5/signatures}",`then the readers will include the PCs twice, since the PCs are the signatures.
2. Add PCs as Participants of the PC stage so we can decide when to add them as signatures and when not to. 

@melisabok thoughts?

**Comment by melisabok** [comment]
I do think PCs should be able to do anything, maybe in the CustomStage they are invitees, readers but not signatures. They should use the committee group id to sign the edit. 

I would also fix the process function and get the number from the forum note, I wouldn't rely on the signatures id or invitation id.
