### ISSUE TITLE
ARR: Set custom max papers to zero for non-responders

### ISSUE THREAD

**Issue by haroldrubio** [openreview/openreview-py#2100]
The matcher does not retrieve value 0 edges if the edge invitation has the default set to 0 for the weight. Either this must be changed in the matcher, or custom max papers for people who don't respond should explicitly be set to 0 when setting up the reassignment data.

**Comment by melisabok** [comment]
instead of creating the edges for all the reviewers we will try to support this in the matching system: https://github.com/openreview/openreview-matcher/pull/282

**Comment by haroldrubio** [comment]
Resolved after merging https://github.com/openreview/openreview-matcher/pull/282
