### ISSUE TITLE
InvalidIssuerError when trying to create a new client

### ISSUE THREAD

**Issue by dhruvrnaik** [openreview/openreview-py#2119]
I am getting an InvalidIssuerError when I try to instantiate a client using this snippet:

```
# API V2
client = openreview.api.OpenReviewClient(
    baseurl='https://api2.openreview.net/',
    username=<your username>,
    password=<your password>
)
```

I manually inspected the response payload, and see that the api response token payload has issuer = "openreview-1695661255950", while the `_handle_token` expects issuer="openreview" and thus raising the `InvalidIssuerError` error.

Any idea on how I can fix this?

**Comment by carlosmondra** [comment]
Hello @dhruvrnaik, thanks for reporting this issue. How did you install openreview-py?

**Comment by dhruvrnaik** [comment]
Hi, it was a simple pip install. Followed the instructions in the readme. The version is 1.39.3

**Comment by carlosmondra** [comment]
I'm trying to reproduce the issue but haven't been able to do it. What python version are you using?

**Comment by dhruvrnaik** [comment]
> I'm trying to reproduce the issue but haven't been able to do it. What python version are you using?
> What operation are you making after instantiating the client (the one that fails)?
> I suppose instantiating the client instantiation is not a problem given that you are able to see the issuer.

Hey. Instantiating the client was the issue. To debug, I sent a POST request to the api directly, and inspected the payload to find the issuer.
I tried again today, and had no issues, and the issuer seemed to match today. 

Seems like you've already addressed this with a fix, thank you!
