### ISSUE TITLE
ARR: Single-use scripts run multiple times

### ISSUE THREAD

**Issue by haroldrubio** [openreview/openreview-py#2125]
The script `setup_tracks_and_reassignments` will run if any new reference is posted with the ARR_Configurator invitation and the cdate has passed already. There should be a check for this script, and any other single-use script to prevent running this multiple times

**Comment by melisabok** [comment]
Let's check if the edges were already created and don't run it again:

```
    if cdate > now or client.get_edges_count(some invitation) > 0:
        ## invitation is in the future, do not process
        print('invitation is not yet active and no child invitations created', cdate)
        return
```

**Comment by haroldrubio** [comment]
After some testing in my environment, it seems like the script actually does not run twice. When I reported the issue, it must have been because it was re-ran by posting an edit instead of the `ARR_Configuration` button which caused the dates to be out of sync

I don't think this change is necessary anymore - unless it would be good to have this second check anyway?
