### ISSUE TITLE
ARR: Update emergency aggregate score workflow

### ISSUE THREAD

**Issue by haroldrubio** [openreview/openreview-py#2127]
When a user submits an emergency reviewer or metareviewer form, the process function updates all aggregate scores by adding 10, but this destroys the meaning of the previous aggregate scores, especially when the emergency reviewing period has not yet started.

The new proposed solution is to compute aggregate scores by:
1. Posting these scores to a new edge invitation `Emergency_Score`
2. Sum across the affinity scores, instead of just the aggregate scores
3. Wait until the reviewing deadline passes, and then compute the scores to avoid confusion during the regular reassignment period

**Comment by melisabok** [comment]
Let's use the same value than the Aggregate Score and post a new edge with the invitation Emergency_Score.

The edge browser will let users to sort reviewers by Emergency_Score.

**Comment by haroldrubio** [comment]
Resolved by #2185
