### ISSUE TITLE
ARR: Change emergency reviewing form to allow multiple areas

### ISSUE THREAD

**Issue by jkkummerfeld** [openreview/openreview-py#2198]
For June onwards, the editors would like people volunteering to be emergency reviewers to say they can do so in multiple areas.

I believe this just requires editing this line (though maybe there is also post-processing logic that is affected?):

https://github.com/openreview/openreview-py/blob/e4d06e94984866d47051dc90cdba410cca6d2aab/openreview/stages/arr_content.py#L1990

**Comment by melisabok** [comment]
input but must a checkbox and type must a string[] in order to allow multiple values

**Comment by jkkummerfeld** [comment]
Yes, AC too, thanks for confirming
