### ISSUE TITLE
ARR: Change review form certification question to be a checkbox

### ISSUE THREAD

**Issue by jkkummerfeld** [openreview/openreview-py#2199]
At the moment, the ARR review form has a question where reviewers have to certify they have written the review themselves. This should be changed to be a checkbox, rather than requiring them to write anything.

I believe it just involves edits here:

https://github.com/openreview/openreview-py/blob/e4d06e94984866d47051dc90cdba410cca6d2aab/openreview/stages/arr_content.py#L1501

**Comment by melisabok** [comment]
I strongly agree about this, we will make the change ASAP.

Do you have a description for this checkbox? something like:

`I certify that the review I entered accurately reflects my assessment of the work. If you used any type of automated tool to help you craft your review, I hereby certify that its use was restricted to improving grammar and style, and the substance of the review is either my own work or the work of an acknowledged secondary reviewer.`

**Comment by jkkummerfeld** [comment]
That looks good, thanks!
