### ISSUE TITLE
Feature Missing for ARR - Emailing Area Chairs for Missing Checklist

### ISSUE THREAD

**Issue by cryptexcode** [openreview/openreview-py#2222]
A SAC emailed with the following.

> I am trying to follow the instructions to email Area Chairs of submissions who have not yet completed their checklist but encountering difficulties.
> There seems to be two ways: one is to select the submissions for which this is the case, and then send an email to all ACs of these submissions. This option seems to be for missing reviews and for emailing reviewers only, however, as far as I can tell from the platform.
> The other is to select ACs to email under the "area chair status tab": I just do not see such a tab anywhere on my console.

**Comment by melisabok** [comment]
It should be fixed here:

https://github.com/openreview/openreview-web/pull/2011
https://github.com/openreview/openreview-py/pull/2224

**Comment by melisabok** [comment]
SACs can filter out the submissions using the query `+actionEditorChecklistCount =0` then select the filtered papers and click on "Message" -> "All Area Chairs of selected submissions"

Please note an email will be sent to each submission assigned to the AC. 

<img width="600" alt="Screen Shot 2024-07-02 at 2 14 11 PM" src="https://github.com/openreview/openreview-py/assets/545506/42f3dd6e-a268-4f8b-9768-e72e27898864">
