### ISSUE TITLE
ARR Previous URL field renders incorrectly

### ISSUE THREAD

**Issue by cryptexcode** [openreview/openreview-py#2226]
For the re-submissions, when the submission page shows the previous url field, the url renders incorrectly. 
For example, 
<img width="437" alt="image" src="https://github.com/openreview/openreview-py/assets/2657596/7d358b06-88cc-49ea-a82c-e544baa0a0e9">

The URL should be openreview.net/forum?id=QIWLLEs8My, not //forum/?id=QIWLLEs8My

**Comment by melisabok** [comment]
it seems the user entered the url with double /:

https://api2.openreview.net/notes?id=eMUKOywNK3

The regex that validates this value should be fine: https://github.com/openreview/openreview-py/blob/master/openreview/stages/arr_content.py#L201

@celestemartinez was this submission posted before the validation was enabled?

**Comment by celestemartinez** [comment]
It looks like the validation was not used for the June cycle. I am checking why the submisison invitation was not updated to include this validation once this was deployed.

**Comment by melisabok** [comment]
it looks like ARR is using another pre process validation: https://github.com/openreview/openreview-py/blob/master/openreview/arr/process/submission_preprocess.py

@haroldrubio can you update it with the version located here? https://github.com/openreview/openreview-py/blob/master/openreview/venue/process/submission_commitments_preprocess.py
