### ISSUE TITLE
Access to resubmissions by authors.

### ISSUE THREAD

**Issue by cryptexcode** [openreview/openreview-py#2227]
We got this issue in a ticket for ARR.

```
In my assigned ARR June papers, there are two indicated resubmissions (1524 and 4291). However, when I clicked the previous link of submission 4291, I received the 403 error. Additionally, I cannot see previous comments of both resubmissions. I wonder, is this on purpose? If not, will you please help release the previous page (so that I can review them as resubmissions)?  Thanks.
```

**Comment by melisabok** [comment]
Is this happening because the reviewer is not the same one from the previous submission?

**Comment by cryptexcode** [comment]
For 1524, the reviewers are the same, but not for 4291.

**Comment by melisabok** [comment]
I'm not sure if this is supported in the current workflow.

We need to think a way to give access to reviewers that weren't reviewers in the previous submissions. @haroldrubio let's discuss this.

**Comment by haroldrubio** [comment]
@cryptexcode It was decided that reviewers who have not yet submitted a review cannot view the reviews of the previous submission to avoid biasing of their reviews. We can't change the error message that appears but the reviewers should be notified that this will happen.

Maybe either in the kickoff email or a small message at the top of the reviewer console?
