### ISSUE TITLE
Add ethics reviewing domain fields on deployment

### ISSUE THREAD

**Issue by haroldrubio** [openreview/openreview-py#2301]
These fields get populated after the ethics review stage is run but we can populated these field on deployment since this information is asked for in the request form

https://github.com/openreview/openreview-py/blob/8f5e148bff40b657b03b9a304a5de2abd64e8c21/openreview/venue/group.py#L263-L269

**Comment by melisabok** [comment]
I think we would need to fix this ASAP because next time the ARR venue request is being used the ethics_chair_id value that you added to the domain will be removed.
