### ISSUE TITLE
The account cannot be activated because I was asked to add an organization email address, but I don't have an organization email address at the moment

### ISSUE THREAD

**Issue by ghaochen** [openreview/openreview-py#2322]
My non-organization mailbox has not been activated successfully, and the corresponding URL link has been added, what is the reason?

**Comment by carlosmondra** [comment]
Hello @ghaochen, 

This repo is for issues related to the openreview-py library. Because it is necessary for you to show personal information like your email/username, please send us an email to info@openreview.net.

Thanks
