### ISSUE TITLE
A question about API version

### ISSUE THREAD

**Issue by bwnjnOEI** [openreview/openreview-py#2341]
I found that the `JSON` formats returned by different API versions(v1 or v2) are not the same, what method can be used to distinguish which version to use, is it the time of paper publication?

**Comment by carlosmondra** [comment]
I suppose you are talking about notes. If that's the case, I'm afraid that you need to try both clients (API v1 client and API v2 client) and see which returns the Note you are looking for.

**Comment by bwnjnOEI** [comment]
Yes, I'm talking about note, and I found that some papers only have v1(or v2) with return values, while another one doesn't, so the official doesn't specify which one to choose, resulting in needing to try both versions.

**Comment by carlosmondra** [comment]
I am not sure I follow your question now. If you explain to me what you are trying achieve, I can better assist you
