### ISSUE TITLE
Change contact_email validation to allow only one email 

### ISSUE THREAD

**Issue by celestemartinez** [openreview/openreview-py#2380]

**Comment by celestemartinez** [comment]
We are currently using: 
> 'value-regex': r'([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,},){0,}([a-z0-9_\-\.]{2,}@[a-z0-9_\-\.]{2,}\.[a-z]{2,})',

I am trying to use this regex instead:
> "value-regex": "([a-z0-9_\\-\\.]{2,}@[a-z0-9_\\-\\.]{2,}\\.[a-z]{2,})",

but I get the following error when trying to add multiple emails: `contact_email does not meet requirements. It cannot be shorter than 2 characters.`

@carlosmondra you know which regex I should be using?

**Comment by carlosmondra** [comment]
Since this is API 1, I would add it to the [`regexTranslations.js`](https://github.com/openreview/openreview-api-v1/blob/master/helpers/regexTranslations.js) file. Let me know if you need help with it.
