### ISSUE TITLE
Question about Reviewer Score Update

### ISSUE THREAD

**Issue by QiyaoWei** [openreview/openreview-py#2449]
Many thanks for maintaining this wonderful repository! I know how to access the paper abstract, the reviews, and the meta-reviews from the Openreview API. Is it possible to access the author rebuttals + reviewer responses (score updates)? I was not able to find documentation about that. Many thanks!

**Comment by carlosmondra** [comment]
This will depend on the venue. Each venue has its own configuration. If you can access that information with your credentials through the UI, then you should be able to use the API to get them too.

**Comment by QiyaoWei** [comment]
I will answer my own question here. Basically it's about finding the right keys to access the data

```
#first you need to instantiate v2 client
#get all submissions
submissions = client.get_all_notes(invitation=venue_name_here,details = 'replies')

#get all official comments
official_comments=[]
for s in submissions:
    official_comments.extend([r for r in submission.details['replies'] if r['invitations'][0].endswith('Official_Comment')])

#get author comments
author_comments = [r for r in official_comments if any('Authors' in mem for mem in r['signatures'])]

#similar for the reviews
#you have to get all the reviews first
#get the ID for the first review
example_review = reviews[0]
review_id = example_review.id

#get the revisions
edits = client.get_note_edits(review_id)
```
