### ISSUE TITLE
PC Console: export data to CSV files

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#296]
The data is all in memory and it can be exported by the PC chairs for their analysis.

**Comment by zbialecki** [comment]
I looked into this a little and apparently it is possible to generate and trigger file downloads on the client side. See this answer on StackOverflow (https://stackoverflow.com/a/33542499/125836) and this library on Github (https://github.com/eligrey/FileSaver.js).

What columns and data should the CSV contain? Do we have an example file?

**Comment by melisabok** [comment]
Yes, I've looking for examples too and it seems we wouldn't need a library to export a csv file. 

The idea is to export the status of each paper so the Program Chairs can do their own decisions, we can create a different export per tab or just have a single button:

```
Paper id, paper number, paper title, reviewer names, reviewer ratings, reviewer confidences, meta-review recommendation
```
@mohituniyal @pmandler could you provide a better example?
