### ISSUE TITLE
Program chairs that are also authors can see their reviewer assignment

### ISSUE THREAD

**Issue by pmandler** [openreview/openreview-py#330]
I logged on as Pascal Bercher and looked at one of his papers - he can see the "ICAPS 2019 Workshop Hierarchical Planning Paper Assignment" for his paper which is displayed right below the anonymized reviews.

**Comment by melisabok** [comment]
Are you talking about the matching browser?

**Comment by pmandler** [comment]
No paper assignments show up on the forum page itself if you are a program chair.

**Comment by melisabok** [comment]
I see, yes, that is data that comes from the matching system. May be we need to set the Author group as nonreaders but if he decides to run the matching, this papers won't get any assignment because the matching system is being run with his permissions.

**Comment by pmandler** [comment]
Can we just not show it on the forum page?

**Comment by melisabok** [comment]
may be, but he can still see them in the matching browser
