### ISSUE TITLE
Get profile references

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#358]
Currently ```client.get_references(id='~Melisa_Bok1')``` returns a list of references notes and we should return a list of reference profiles. 

We can create a new a new function:

```
def get_profiles_references(referent):
    return Profile.from_json(result)
```

**Comment by mspector** [comment]
we could also check that the referent starts with "~", and if so, return a Profile object. What do you think?

**Comment by melisabok** [comment]
That could work but we are planning to support multiple levels of references.
