### ISSUE TITLE
AC Console: doesn't show assigned reviewers

### ISSUE THREAD

**Issue by pmandler** [openreview/openreview-py#387]

**Comment by pmandler** [comment]
![Screen Shot 2019-08-08 at 9 33 30 AM](https://user-images.githubusercontent.com/15744077/62707608-a9ca2480-b9bf-11e9-9423-de221d5a4a02.png)

**Comment by mohituniyal** [comment]
@pmandler Can I get some steps to reproduce the issue.

**Comment by mohituniyal** [comment]
@pmandler  Please reopen this issue when you see it again. Closing it for now.
