### ISSUE TITLE
Change user agent

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#500]
Currently the value is: 'test-create-script'. 

Could we define one for the python library? 

@zbialecki @carlosmondra

**Comment by zbialecki** [comment]
I agree this would be nice. My suggestion would be "openreview-py-script".

**Comment by melisabok** [comment]
I'm seeing in the live errors a lot of requests coming from this user agent.

**Comment by zbialecki** [comment]
Is someone trying to crawl the site using the python library?

**Comment by melisabok** [comment]
Well, there are a lot researchers using the library.

**Comment by melisabok** [comment]
Do you know why we have 'node-superagent' here?

https://github.com/openreview/openreview/blob/master/middleware/error.js#L135

**Comment by zbialecki** [comment]
Yes, I added that because while some of the tests use the create-test-script UA, a few don't set the  UA and default to node-superagent (which is from the package used to make the requests).
