### ISSUE TITLE
Immediate error, openreview has no attribute Client

### ISSUE THREAD

**Issue by alecjacobson** [openreview/openreview-py#533]
If I issue:
```
import openreview
from __future__ import print_function
c = openreview.Client(baseurl='https://openreview.net')
```

I immediately get an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'openreview' has no attribute 'Client'
```

I'm trying to run this example:
https://openreview-py.readthedocs.io/en/latest/get_all_venues.html

**Comment by alecjacobson** [comment]
I had (only) issued:

```pip install openreview
```

If I (also) issue:

```pip install openreview-py
```

Then it seems to work.

(Would be nice to catch this more gracefully).

**Comment by alecjacobson** [comment]
Spoke to soon, I only made it one line through the example before getting a similar error:

```
c = openreview.Client(baseurl='https://openreview.net')
venues = openreview.get_all_venues(c)
```

produces:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'openreview' has no attribute 'get_all_venues'
```

Is there something besides `pip install openreview-py` that I need to do?

**Comment by alecjacobson** [comment]
Maybe the line in the example should be:

```
venues = openreview.tools.get_all_venues(c)
```
?

**Comment by melisabok** [comment]
Hi Alec,

Our official python library is [openreview-py](https://pypi.org/project/openreview-py/) and you are right, the documentation is wrong, you need to use `tools`. I fixed here #534 

Thanks for reporting the issue.

Best,

Melisa

**Comment by mohituniyal** [comment]
Issue resolved at merge https://github.com/openreview/openreview-py/pull/534. Closing this issue.

**Comment by RiceYangCoder** [comment]
I can't solve the same problem, and I successfully download the openreview-py, and imported openreview.
But can't find the attribute Client.

**Comment by RiceYangCoder** [comment]
Can you do me a favor?

**Comment by carlosmondra** [comment]
Hi @RiceYangCoder did you follow these instructions to install openreview-py?
```
git clone https://github.com/openreview/openreview-py.git
cd openreview-py
pip install -e .
```

**Comment by RiceYangCoder** [comment]
@carlosmondra I tired and I can't either
`AttributeError: module 'openreview' has no attribute 'Client'`
I was originally using
`pip install openreview-py`
I failed ，maybe I'm using a Chinese network and don't have access to the external network. I successfully download the openreview-py, and I can import it.Packages that can display openreview in my environment. The version is 1.6.2.

**Comment by RiceYangCoder** [comment]
@carlosmondra I tried what you said by external network ,  but it also failed.
'AttributeError: module 'openreview' has no attribute 'Client'

**Comment by carlosmondra** [comment]
@RiceYangCoder: 

> @carlosmondra I tired and I can't either `AttributeError: module 'openreview' has no attribute 'Client'` I was originally using `pip install openreview-py` I failed 

If you did `pip install openreview` at some point, maybe you installed the [wrong package](https://pypi.org/project/openreview/). Take a look at `pip list` and see if it's there. If it is, then you have to completely remove that package.

> maybe I'm using a Chinese network and don't have access to the external network.

No, this has nothing to do with it. The error `AttributeError: module 'openreview' has no attribute 'Client'` is an error coming from your installation of the package.

> @carlosmondra I tried what you said by external network , but it also failed. 'AttributeError: module 'openreview' has no attribute 'Client'

As I said before, the network is not the issue. Your installation is broken. I'd suggest you follow the steps I mentioned in a new  and clean python environment.

**Comment by mashaonian** [comment]
If you run into the error ‘AttributeError: module ‘openreview’ has no attribute ‘Client’’, it is advised to set up a new environment and execute ‘pip install openreview-py
