### ISSUE TITLE
API does not work on ICLR2020

### ISSUE THREAD

**Issue by Tristan-Chow** [openreview/openreview-py#536]
Hi,
   I try this API on newly-released ICLR2020 and find it returns an empty list.
   Thanks!

**Comment by mohituniyal** [comment]
Hey @Tristan-Chow, can you let us know what api call you made to get the iclr2020 details?

**Comment by Tristan-Chow** [comment]
Hey,
    Here are the codes I tried
    ```
    import openreview as op
    client = op.Client(baseurl='https://openreview.net')
    paper123_reviews = client.get_notes(
        invitation='ICLR.cc/2020/Conference/-/Paper1/Official_Review')
    forum_comments = client.get_notes(forum="Symlf87uG")
    ```
    The codes mostly follow your documentation, with some parameters changed. I tried to get papers' information by these two approaches and it returns None.
    The op.tools.iterget_notes also returns nothing.
    Thanks for your help!

**Comment by EagleW** [comment]
Same problem, cannot get any review for ICLR 2020

**Comment by melisabok** [comment]
The invitation id has slightly changed this year, please try:

```
paper123_reviews = client.get_notes( invitation='ICLR.cc/2020/Conference/Paper1/-/Official_Review')
```

then replace the paper number with the submission that you want to get the reviews or:

```
firt_1000_reviews = client.get_notes( invitation='ICLR.cc/2020/Conference/Paper.*/-/Official_Review')
```

it returns the first 1000 reviews, you can get the next page using the parameter 'offset' or use `openreview.tool.iterget_notes`

**Comment by EagleW** [comment]
Thank you very much! It works!

**Comment by nd7141** [comment]
Thank you. It works. You should put the link somewhere in the documentation so that others can find it.

**Comment by mohituniyal** [comment]
Thanks for the suggestion @nd7141 . We will update the documentation.
Closing this issue.
