### ISSUE TITLE
PC Console: show total number of active submission

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#598]
There is no way for the PCs to know how many active submission are.

**Comment by zbialecki** [comment]
I was thinking this information could either be displayed in the header, directly under "Program Chair Console" (replacing the instruction text, which I don't think is useful) or in the configuration tab, above the links.

In terms of data to display, would it be helpful to show number of withdrawn number of desk rejected submissions as well?

**Comment by melisabok** [comment]
Yes, we would like also to show the progress of the bids, recommendation, reviews and meta reviews 😆

**Comment by zbialecki** [comment]
How would you calculate that? The percentage of reviewers/ACs that completed the minimum number of bids? For reviews, the number of papers with all reviews completed?

**Comment by melisabok** [comment]
> The percentage of reviewers/ACs that completed the minimum number of bids? 

I would count the amount of Reviewer/ACs with at least one bid over the total of Reviewers/ACs.

another option is to use the rule con task completion. The amount of users who bids more than `taskCompletionCount`.

>For reviews, the number of papers with all reviews completed?

Yes, that could one option. Or can be the amount of reviewers completed over the total amount of reviews.

**Comment by melisabok** [comment]
We have all these information in the UI because we load all the data. Showing progress or some stats can be very helpful, may be we can add another tab.

**Comment by melisabok** [comment]
Another option is to show the progress next to each invitation rendered in the configuration tab.

**Comment by zbialecki** [comment]
I was thinking something like this for the configuration tab:

<img width="1161" alt="Screen Shot 2020-03-13 at 9 31 51 AM" src="https://user-images.githubusercontent.com/86174/76625428-94951580-650d-11ea-8689-5c592bf51af7.png">

**Comment by melisabok** [comment]
I like it!

I would show the percentage next to each number. We also need to keep the link to the configuration now somewhere. 

I'm asking the rest of the team for feedback: @celestemartinez @carlosmondra @xkopenreview @mohituniyal
