### ISSUE TITLE
allow users to build and test a set of OpenReview objects before posting to the live site

### ISSUE THREAD

**Issue by mspector** [openreview/openreview-py#61]
There should be a way for users to test their code before having to deploy it on the live site. It's easy for us as developers to do it, because we can install a local instance of OpenReview and test everything there. But among our users, even the small subset that will be actually running openreview scripts are unlikely to install and setup their own openreview server.

We might want to do something like tensorflow's "graph" and "session" structure. We could let users build an OpenReview "setup" of some kind, and then create an endpoint to allow the testing of that structure (or maybe even have a dedicated test instance?). We could then run some form of unit test on the conference structure. (unit tests for conferences are an entirely other matter)

As an alternative to all of this, we could open source the OpenReview code base and make it very easy to spin up a local server. (this might actually be the easiest solution)

**Comment by melisabok** [comment]
dev.openreview.net is available now.
