### ISSUE TITLE
PC Console: hide Bid section if venue is not using it

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#655]
I think we should hide this section, there are a lot of venues doing manual assignment and this can be confusing.

We have two ways to check when to show this:

- If invitation is created.
- Check in configuration note if `paper_matching` has the value `Reviewer Bid Scores`.

**Comment by zbialecki** [comment]
Currently if the constant `BID_NAME` is empty (null, or empty string) all bidding related info is turned off. I would prefer to modify the builder to properly set `BID_NAME` rather than doing lots of extra checks in the PC console.

**Comment by melisabok** [comment]
I can do that.

**Comment by zbialecki** [comment]
Closed by #750
