### ISSUE TITLE
PC Console: remove reviewer assignment link if venue decides manual assignment

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#656]
This option is always shown:

<img width="418" alt="Screen Shot 2020-05-07 at 8 50 59 AM" src="https://user-images.githubusercontent.com/545506/81297420-384bff00-9041-11ea-8d69-1b7435765c84.png">

I think we can check if the configuration note has the option of manual assignment o not.

**Comment by zbialecki** [comment]
Closed by #750
