### ISSUE TITLE
Builder: create paper groups in each stage

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#657]
Same as we do when we create blind submissions, we should call to `conference.create_paper_groups(authors=True, reviewers=True)` when the venue is single blind.

**Comment by mohituniyal** [comment]
Now that we are calling `setup_post_submission_stage` (changes from #701), this is fixed. 
The method `setup_post_submission_stage` checks if the venue is not double blind and if so, it calls `conference.create_paper_groups(authors=True, reviewers=True, area_chairs=True)`
