### ISSUE TITLE
Builder: Author group empty

### ISSUE THREAD

**Issue by celestemartinez** [openreview/openreview-py#695]
For a single-blind conference, paper author groups were created correctly, and main author group was created as well, but it was empty.

**Comment by mohituniyal** [comment]
@celestemartinez Did you see this happen when you run `conference.create_paper_groups` ? I tried doing that but could not reproduce the issue.

**Comment by mohituniyal** [comment]
I think I see what happened. The `create_paper_groups` method is only called in method `create_blind_submissions`. So, there might be an issue with Single blind conferences. Looking into how to fix this.
