### ISSUE TITLE
Getting first submission as well as last version, post-revision of conference submissions

### ISSUE THREAD

**Issue by limorigu** [openreview/openreview-py#717]
Thank you all for a great python API for interacting with openReview (in particular, used so for access to ICLR 2019 submissions). 

I did have a question about the option of getting both the first and last submissions associated with each forum id. Looking at the source code, I assumed get_references + get_pdf with the parameter is_reference=True should get me there. However, I'm getting some unexpected behaviour, and currently am unable to get to the relevant ids to retrieve the PDF for older submissions given a forum id. I can of course do some scraping to find the relevant ids by looking at the base_url+/revisions?id=<forum_id>, but I was hoping for a more elegant way that as part of the API. 

If one does not exist, no worries, I can work around it. Otherwise, if I missed it, apologies, and hoping you can point me to the right direction. 

Many thanks!

**Comment by mohituniyal** [comment]
You are indeed using the correct API calls i.e. `get_references` and `get_pdf`.

So, the get_references will get you versions of the forum note. But, note that with double-blind venues the submission versions are of the original note and not the forum note which is a blinded copy of the original note.

For a forum, you can get the original note's id by doing:
`original_note_id = client.get_note(id=<forum_note_id>).original`

And then get all the references for this original_note:
`references = client.get_references(referent=<original_note_id>)`

With that you can get the pdf files (in binary) for each of these references one by one and write them to a file:
>`pdf_content = client.get_pdf(id=references[0].id, is_reference=True)`
> `with open('file0.pdf', 'wb') as f:`
>> `f.write(pdf_content)`

Let us know if this works.

**Comment by limorigu** [comment]
Thanks so much for the prompt reply! The logic makes sense now. 

To make it work for the ICLR 2019 example, in fact, what works for me is to just run 
`references = client.get_references(referent=<forum_id>, original=True)`

and iterate over `references` as you suggested to save each pdf. If I try to run the first command you suggested, i.e. 
`original_note_id = client.get_note(id=<forum_note_id>).original`

and then use `original_note_id` in my call to `get_references`, I actually get an empty list in this case. Perhaps it changes a bit from conference to conference?

Anyway, thanks so much for your help. I get the structure better now. Hope it helps others too. Cheers!
