### ISSUE TITLE
ICLR decision invitations over the years

### ISSUE THREAD

**Issue by limorigu** [openreview/openreview-py#718]
Dear OpenReview, 

Thanks again for this very convenient API and your continual support. I noticed the invitation format for ICLR (and potentially other conferences) changed through the years, in particular those that allow access to accept/reject decisions.

In 2019 it was: `ICLR.cc/2019/Conference/-/Paper.*/Meta_Review`
In 2020: `ICLR.cc/2020/Conference/Paper.*/-/Decision`

Any pointers as to 2018 and 2017? Or how to more generally look those up?

Many thanks,
Limor

**Comment by limorigu** [comment]
Hmm for those wondering about 2018, the answer is to get all acceptance decisions together (not indexed by paper #):

`decisions = openreview.tools.iterget_notes(
        client, invitation='ICLR.cc/2018/Conference/-/Acceptance_Decision')`

And then you can access specific ones via forum id. Hope it helps others out there!

**Comment by mohituniyal** [comment]
@limorigu The nomenclature used for OpenReview invitation ids has indeed evolved.

Here's a list of all ICLR conference invitations for final decisions:
1. 2020: `ICLR.cc/2020/Conference/-/Paper[0-9]*/Decision`
2. 2019: `ICLR.cc/2019/Conference/-/Paper[0-9]*/Meta_Review`
3. 2018: `ICLR.cc/2018/Conference/-/Acceptance_Decision` and then filter out decisions by the `note.forum`
4. 2017: `ICLR.cc/2017/conference/-/paper[0-9]*/acceptance`

A simple way to find these invitations is to go to a submission from the venue on OpenReview and locate one of the decision notes on the forum page. The dropdown filters at the top of the replies can quickly show you all the invitations used by the replies on the page.
Once you have found the decision note, you can get the note using the id (`decision_note = get_note(id=note.id)`) and that gives you the invitation (in `decision_note.invitation`).

Hope this helps.

**Comment by limorigu** [comment]
That indeed helps! Many thanks, I can close the issue now. Hope it helps others out there too!
