### ISSUE TITLE
Request form: remove the PCs as writers when the venue is deployed

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#804]
We need to force the PCs to use the 'Revision' button to edit the request form so the process function can propagate the changes.

**Comment by celestemartinez** [comment]
This line used to do it I believe:
https://github.com/openreview/openreview-py/blob/df12b042ddebe1e09616e75319c10dc37860b2fc/openreview/venue_request/process/deployProcess.py#L46

example: https://api.openreview.net/notes?id=mGIRv8fSonp
