### ISSUE TITLE
PC console: scroll position trapped to top when navigating to a different page

### ISSUE THREAD

**Issue by xkopenreview** [openreview/openreview-py#891]
it seems that user won't be able to scroll down for a few seconds when navigating using pagination

https://user-images.githubusercontent.com/60613434/116456302-1ccc9c00-a830-11eb-8b55-7d47f48cf4c7.mp4

**Comment by melisabok** [comment]
@xkopenreview is this an open issue?

**Comment by xkopenreview** [comment]
I thin i can't reproduce this anymore
