### ISSUE TITLE
PC console: unexpected behavior pressing enter key in search input

### ISSUE THREAD

**Issue by xkopenreview** [openreview/openreview-py#893]
it looks like when pressing enter key in search input has the following behavior:
when export button is present, it's having focus and pressing enter key triggers csv download.

https://user-images.githubusercontent.com/60613434/116608421-28d45e80-a901-11eb-8d70-322d4cfc0adb.mp4

when there's no export button, it seems like the switch sort option button is having focus and pressing enter key in search input will reverse sort direction
**this is local env**

**Comment by xkopenreview** [comment]
it looks like the behavior is not consistent 
in prod the sort by option is cleared when enter key is pressed

https://user-images.githubusercontent.com/60613434/116617387-c765bd00-a90b-11eb-8c6e-f1fbeeb978e8.mp4

**Comment by melisabok** [comment]
I fixed this issue in the NeurIPS PC console but I didn't push the change. Zach helped me to find the bug: all the buttons must have the property `type="button"`

**Comment by xkopenreview** [comment]
pressing enter key is clearing sort by dropdown is caused by 
```javaScript
$(container + ' .form-sort').val('Reviewer');
```
in searchResults function
do you know what this does?

my guess is that this is for resetting sort by option, then Reviewer should be changed to 'Reviewer_Name'

**Comment by melisabok** [comment]
@xkopenreview I think this is fixed, can I close this issue?

**Comment by xkopenreview** [comment]
> @xkopenreview I think this is fixed, can I close this issue?

yes
