### ISSUE TITLE
Need more restrictive regex in title

### ISSUE THREAD

**Issue by carlosmondra** [openreview/openreview-py#913]
Currently the regex used in the title uses:
```js
  "title": {
  "description": "Title of paper. Add TeX formulas using the following formats: $In-line Formula$ or $$Block Formula$$",
  "order": 1,
  "value-regex": ".{1,250}",
  "required": true
}
```

which allows empty spaces to be in the title as the only character. We should have a more restrictive regex that does not allow only empty spaces.

```js
content": {
  "title": " ",
  "authorids": [
    "NeurIPS.cc/2021/Conference/Paper<number>/Authors"
  ],
  ...
}
```

![image](https://user-images.githubusercontent.com/12961955/119377796-24daf880-bc83-11eb-95ff-4789f0c3307d.png)

**Comment by melisabok** [comment]
This was causing the issue in the expertise model
