### ISSUE TITLE
Revision process function: reset the authors the members with the values of note.content.authorids

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#926]
Now, we are using the information of the reference to add authors to the author group but if the reference gets deleted the author group is not updated. 

I think we should always get the note and use the note.content.authorids value to set the author members.

**Comment by purujitgoyal** [comment]
@melisabok could you share an example on how to replicate this?

**Comment by melisabok** [comment]
- Author A submits a paper where Author A is an author
- Author A submits a revision(second deadline) where Author A and Author B are authors
- Author A deletes the revision 
- The author group should have Author A as the only member of the group.
