### ISSUE TITLE
Conflicts: take in account the profile publications to compute co-authors relationships

### ISSUE THREAD

**Issue by melisabok** [openreview/openreview-py#966]
Our default implementation to compute conflicts only uses the profile domains to detect conflicts. We should follow the 'neurips' implementation and take in account the publications too.

**Comment by melisabok** [comment]
Conflicts are computed here: 

https://github.com/openreview/openreview-py/blob/master/openreview/conference/matching.py#L253

and here is when we get the profile data to compute the conflicts:

https://github.com/openreview/openreview-py/blob/master/openreview/conference/matching.py#L271

get_neurips_profile_info return a publication key but get_profile_info doesn't. Add this publication key to the result of get_profile_info, by default we should take in account ALL the publications.

**Comment by purujitgoyal** [comment]
Do we want the option to turn it off as well or just make it permanent?

**Comment by melisabok** [comment]
Permanent, our default conflict detection implementation should take in account the author relationship through publication. In the future we could parametrize the last N years we want to get publications. NeurIPS is using only the last 3 years of publications.
